//
//  LegalContent.swift
//  Connected
//

import SwiftUI

enum LegalContent {
    static let privacyPolicy: LocalizedStringKey = """
        This privacy policy applies to the Connected app for mobile devices, operated by Elia Moharer ("Service Provider").
        
        **What information does the Application obtain and how is it used?**
        
        Connected does not operate backend servers and does not collect, log, or sell your personal information. Registration is not required.
        
        The following data stays on your device unless you explicitly send it to an LLM server you configure:
        
        * Chat messages and saved chat history
        * Optional authentication keys for your LLM server
        * Model, endpoint, and profile preferences
        
        When you tap **Find Endpoints**, the app scans your local Wi‑Fi network to discover LLM servers you run. This scan is initiated by you and is not sent to the Service Provider.
        
        When you connect to an LLM server (local network, Tailscale, or Apple Intelligence on supported devices), your messages and any photos you attach are sent directly to that service. The Service Provider does not receive or store those requests.
        
        If you contact the Service Provider by email, any information you include is used only to respond to you.
        
        **Photos**
        
        If you attach photos, they are read from your photo library at your request, resized on device, and sent only to the LLM endpoint you select. The Service Provider does not receive your photos.
        
        **Does the Application collect precise real-time location information?**
        
        No. Connected does not collect GPS or precise location data.
        
        **Do third parties see and/or have access to information obtained by the Application?**
        
        The Service Provider does not receive your chat content or network scan results. Third-party LLM servers you connect to receive the messages and attachments you send to them, under their own policies.
        
        Apple Intelligence, when available, processes requests on device according to Apple's policies.
        
        **What are my opt-out rights?**
        
        Uninstalling the app removes locally stored data from your device. You may request deletion of any information you voluntarily sent to the Service Provider by email at elia.moharer@gmail.com.
        
        **Children**
        
        Connected is not intended for children under 13. The app is not directed at children and the Service Provider does not knowingly collect children's data.
        
        **Security**
        
        You are responsible for securing your device and any LLM servers you connect to. Optional server authentication keys are stored locally on your device.
        
        **Changes**
        
        The Service Provider may update this Privacy Policy from time to time by posting an updated version in the app with a new effective date.
        
        This privacy policy is effective as of 2026-06-15.
        
        **Contact Us**
        
        elia.moharer@gmail.com
        """
    
    static let termsOfService: LocalizedStringKey = """
        These Terms and Conditions apply to the Connected app for mobile devices, operated by Elia Moharer ("Service Provider").
        
        By downloading or using Connected, you agree to these Terms.
        
        **License**
        
        The Service Provider grants you a personal, non-transferable license to use Connected on Apple devices you own or control, subject to these Terms and the Apple Media Services Terms.
        
        **What Connected Does**
        
        Connected is a client that lets you chat with language models you run yourself (for example Ollama or LM Studio), optionally via Tailscale, or with on-device Apple Intelligence when available. The Service Provider does not host models or chat content.
        
        **AI-Generated Content**
        
        Responses are generated by AI models you connect or by Apple Intelligence. They may be inaccurate, incomplete, or inappropriate. Do not rely on AI output for medical, legal, financial, or safety-critical decisions. The Service Provider does not control third-party model output.
        
        **User Content and Acceptable Use**
        
        You are responsible for prompts, photos, and other content you submit through the app. You agree not to use Connected to generate or store content that is illegal, harassing, defamatory, fraudulent, or that infringes others' rights.
        
        Chat content is stored locally on your device. Connected is not a social network; messages are not shared with other Connected users.
        
        **Reporting Content**
        
        You may hide any assistant message from your chat using the flag button. This removes the message from your device only. To report a legal or safety concern about the app itself, contact elia.moharer@gmail.com.
        
        **In-App Purchase**
        
        Connected offers a one-time purchase that unlocks manual custom endpoint entry. All other core features are free. Prices are displayed in the purchase sheet before you buy. Restore purchases is available in the purchase sheet and in Help.
        
        **Data Storage**
        
        Chat histories, settings, and preferences are stored locally on your device. The Service Provider does not operate servers that store your conversations.
        
        **Termination**
        
        You may stop using Connected at any time by deleting the app. The Service Provider may update or discontinue the app as permitted by applicable law.
        
        **Limitation of Liability**
        
        To the fullest extent permitted by law, the Service Provider is not liable for output from third-party models, loss of data stored only on your device, or network issues between your device and servers you configure. Nothing in these Terms limits liability that cannot be excluded under applicable consumer protection law.
        
        **Changes**
        
        The Service Provider may update these Terms by posting a revised version in the app.
        
        These terms are effective as of 2026-06-15.
        
        **Contact Us**
        
        elia.moharer@gmail.com
        """
    
    static let aiDisclaimer = "Responses are AI-generated and may be inaccurate."
    
    static let supportEmail = "elia.moharer@gmail.com"
}
